// Country -> currency/timezone/phone code defaults, plus a curated set of
// regions and cities for African countries. For any country (or region/city)
// not in the list, the UI offers a manual "Other — enter manually" option.

export type CountryInfo = {
  code: string;
  name: string;
  nameFr: string;
  currency: string;
  currencySymbol: string;
  timezone: string;
  phoneCode: string;
  regions?: { name: string; cities: string[] }[];
};

const AFRICA: CountryInfo[] = [
  {
    code: 'CM', name: 'Cameroon', nameFr: 'Cameroun', currency: 'XAF', currencySymbol: 'FCFA',
    timezone: 'Africa/Douala', phoneCode: '+237',
    regions: [
      { name: 'Littoral', cities: ['Douala', 'Edea', 'Nkongsamba', 'Loum'] },
      { name: 'Centre', cities: ['Yaoundé', 'Mbalmayo', 'Bafia', 'Obala'] },
      { name: 'Ouest', cities: ['Bafoussam', 'Dschang', 'Foumban', 'Mbouda'] },
      { name: 'Sud-Ouest', cities: ['Buea', 'Kumba', 'Limbe', 'Tiko'] },
      { name: 'Nord-Ouest', cities: ['Bamenda', 'Kumbo', 'Ndop'] },
      { name: 'Sud', cities: ['Ebolowa', 'Kribi', 'Sangmelima'] },
      { name: 'Adamaoua', cities: ['Ngaoundéré', 'Meiganga', 'Tibati'] },
      { name: 'Est', cities: ['Bertoua', 'Abong-Mbang', 'Batouri'] },
      { name: 'Nord', cities: ['Garoua', 'Guider', 'Pitoa'] },
      { name: 'Extrême-Nord', cities: ['Maroua', 'Kousseri', 'Mokolo', 'Yagoua'] },
    ],
  },
  {
    code: 'SN', name: 'Senegal', nameFr: 'Sénégal', currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Dakar', phoneCode: '+221',
    regions: [
      { name: 'Dakar', cities: ['Dakar', 'Pikine', 'Guédiawaye', 'Rufisque'] },
      { name: 'Thiès', cities: ['Thiès', 'Mbour', 'Tivaouane'] },
      { name: 'Diourbel', cities: ['Diourbel', 'Mbacké', 'Touba'] },
      { name: 'Saint-Louis', cities: ['Saint-Louis', 'Dagana', 'Podor'] },
    ],
  },
  {
    code: 'CI', name: "Côte d'Ivoire", nameFr: "Côte d'Ivoire", currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Abidjan', phoneCode: '+225',
    regions: [
      { name: 'Abidjan', cities: ['Abidjan', 'Cocody', 'Yopougon', 'Plateau'] },
      { name: 'Bas-Sassandra', cities: ['San-Pédro', 'Divo', 'Soubré'] },
      { name: 'Lagunes', cities: ['Dabou', 'Tiassalé'] },
    ],
  },
  {
    code: 'NG', name: 'Nigeria', nameFr: 'Nigeria', currency: 'NGN', currencySymbol: '₦',
    timezone: 'Africa/Lagos', phoneCode: '+234',
    regions: [
      { name: 'Lagos', cities: ['Lagos', 'Ikeja', 'Lekki'] },
      { name: 'FCT', cities: ['Abuja', 'Gwagwalada'] },
      { name: 'Rivers', cities: ['Port Harcourt', 'Bonny'] },
      { name: 'Kano', cities: ['Kano', 'Wudil'] },
    ],
  },
  {
    code: 'KE', name: 'Kenya', nameFr: 'Kenya', currency: 'KES', currencySymbol: 'KSh',
    timezone: 'Africa/Nairobi', phoneCode: '+254',
    regions: [
      { name: 'Nairobi', cities: ['Nairobi', 'Westlands', 'Embakasi'] },
      { name: 'Mombasa', cities: ['Mombasa', 'Malindi', 'Diani'] },
      { name: 'Kisumu', cities: ['Kisumu', 'Ahero'] },
    ],
  },
  {
    code: 'ZA', name: 'South Africa', nameFr: 'Afrique du Sud', currency: 'ZAR', currencySymbol: 'R',
    timezone: 'Africa/Johannesburg', phoneCode: '+27',
    regions: [
      { name: 'Gauteng', cities: ['Johannesburg', 'Pretoria', 'Sandton'] },
      { name: 'Western Cape', cities: ['Cape Town', 'Stellenbosch'] },
      { name: 'KwaZulu-Natal', cities: ['Durban', 'Pietermaritzburg'] },
    ],
  },
  {
    code: 'GH', name: 'Ghana', nameFr: 'Ghana', currency: 'GHS', currencySymbol: '₵',
    timezone: 'Africa/Accra', phoneCode: '+233',
    regions: [
      { name: 'Greater Accra', cities: ['Accra', 'Tema', 'Madina'] },
      { name: 'Ashanti', cities: ['Kumasi', 'Obuasi'] },
    ],
  },
  {
    code: 'ET', name: 'Ethiopia', nameFr: 'Éthiopie', currency: 'ETB', currencySymbol: 'Br',
    timezone: 'Africa/Addis_Ababa', phoneCode: '+251',
    regions: [{ name: 'Addis Ababa', cities: ['Addis Ababa', 'Bole', 'Kazanchis'] }],
  },
  {
    code: 'RW', name: 'Rwanda', nameFr: 'Rwanda', currency: 'RWF', currencySymbol: 'RF',
    timezone: 'Africa/Kigali', phoneCode: '+250',
    regions: [{ name: 'Kigali', cities: ['Kigali', 'Nyarugenge', 'Gasabo'] }],
  },
  {
    code: 'TZ', name: 'Tanzania', nameFr: 'Tanzanie', currency: 'TZS', currencySymbol: 'TSh',
    timezone: 'Africa/Dar_es_Salaam', phoneCode: '+255',
    regions: [{ name: 'Dar es Salaam', cities: ['Dar es Salaam', 'Kigamboni'] }],
  },
  {
    code: 'UG', name: 'Uganda', nameFr: 'Ouganda', currency: 'UGX', currencySymbol: 'USh',
    timezone: 'Africa/Kampala', phoneCode: '+256',
    regions: [{ name: 'Kampala', cities: ['Kampala', 'Entebbe', 'Mukono'] }],
  },
  {
    code: 'ML', name: 'Mali', nameFr: 'Mali', currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Bamako', phoneCode: '+223',
    regions: [{ name: 'Bamako', cities: ['Bamako', 'Kati'] }],
  },
  {
    code: 'BF', name: 'Burkina Faso', nameFr: 'Burkina Faso', currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Ouagadougou', phoneCode: '+226',
    regions: [{ name: 'Centre', cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'] }],
  },
  {
    code: 'BJ', name: 'Benin', nameFr: 'Bénin', currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Porto-Novo', phoneCode: '+229',
    regions: [{ name: 'Littoral', cities: ['Cotonou', 'Porto-Novo', 'Abomey-Calavi'] }],
  },
  {
    code: 'TG', name: 'Togo', nameFr: 'Togo', currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Lome', phoneCode: '+228',
    regions: [{ name: 'Maritime', cities: ['Lomé', 'Tsévié', 'Aného'] }],
  },
  {
    code: 'CG', name: 'Congo', nameFr: 'Congo', currency: 'XAF', currencySymbol: 'FCFA',
    timezone: 'Africa/Brazzaville', phoneCode: '+242',
    regions: [{ name: 'Brazzaville', cities: ['Brazzaville', 'Pointe-Noire'] }],
  },
  {
    code: 'CD', name: 'DR Congo', nameFr: 'RD Congo', currency: 'CDF', currencySymbol: 'FC',
    timezone: 'Africa/Kinshasa', phoneCode: '+243',
    regions: [{ name: 'Kinshasa', cities: ['Kinshasa', 'Lubumbashi', 'Goma'] }],
  },
  {
    code: 'GA', name: 'Gabon', nameFr: 'Gabon', currency: 'XAF', currencySymbol: 'FCFA',
    timezone: 'Africa/Libreville', phoneCode: '+241',
    regions: [{ name: 'Estuaire', cities: ['Libreville', 'Port-Gentil'] }],
  },
  {
    code: 'MA', name: 'Morocco', nameFr: 'Maroc', currency: 'MAD', currencySymbol: 'DH',
    timezone: 'Africa/Casablanca', phoneCode: '+212',
    regions: [
      { name: 'Casablanca-Settat', cities: ['Casablanca', 'Mohammedia', 'Settat'] },
      { name: 'Rabat-Salé-Kénitra', cities: ['Rabat', 'Salé', 'Kénitra'] },
      { name: 'Marrakech-Safi', cities: ['Marrakech', 'Safi', 'Essaouira'] },
    ],
  },
  {
    code: 'EG', name: 'Egypt', nameFr: 'Égypte', currency: 'EGP', currencySymbol: 'E£',
    timezone: 'Africa/Cairo', phoneCode: '+20',
    regions: [
      { name: 'Cairo', cities: ['Cairo', 'Giza', 'Helwan'] },
      { name: 'Alexandria', cities: ['Alexandria', 'Borg El Arab'] },
    ],
  },
  {
    code: 'DZ', name: 'Algeria', nameFr: 'Algérie', currency: 'DZD', currencySymbol: 'DA',
    timezone: 'Africa/Algiers', phoneCode: '+213',
    regions: [{ name: 'Alger', cities: ['Alger', 'Bab Ezzouar', 'Hydra'] }],
  },
  {
    code: 'TN', name: 'Tunisia', nameFr: 'Tunisie', currency: 'TND', currencySymbol: 'DT',
    timezone: 'Africa/Tunis', phoneCode: '+216',
    regions: [{ name: 'Tunis', cities: ['Tunis', 'Sfax', 'Sousse'] }],
  },
  {
    code: 'LY', name: 'Libya', nameFr: 'Libye', currency: 'LYD', currencySymbol: 'LD',
    timezone: 'Africa/Tripoli', phoneCode: '+218',
    regions: [{ name: 'Tripoli', cities: ['Tripoli', 'Misrata'] }],
  },
  {
    code: 'SD', name: 'Sudan', nameFr: 'Soudan', currency: 'SDG', currencySymbol: 'SDG',
    timezone: 'Africa/Khartoum', phoneCode: '+249',
    regions: [{ name: 'Khartoum', cities: ['Khartoum', 'Omdurman'] }],
  },
  {
    code: 'SS', name: 'South Sudan', nameFr: 'Soudan du Sud', currency: 'SSP', currencySymbol: 'SSP',
    timezone: 'Africa/Juba', phoneCode: '+211',
  },
  {
    code: 'TD', name: 'Chad', nameFr: 'Tchad', currency: 'XAF', currencySymbol: 'FCFA',
    timezone: 'Africa/Ndjamena', phoneCode: '+235',
    regions: [{ name: 'N\'Djamena', cities: ["N'Djamena", 'Moundou'] }],
  },
  {
    code: 'CF', name: 'Central African Republic', nameFr: 'République Centrafricaine', currency: 'XAF', currencySymbol: 'FCFA',
    timezone: 'Africa/Bangui', phoneCode: '+236',
  },
  {
    code: 'GQ', name: 'Equatorial Guinea', nameFr: 'Guinée Équatoriale', currency: 'XAF', currencySymbol: 'FCFA',
    timezone: 'Africa/Malabo', phoneCode: '+240',
  },
  {
    code: 'AO', name: 'Angola', nameFr: 'Angola', currency: 'AOA', currencySymbol: 'Kz',
    timezone: 'Africa/Luanda', phoneCode: '+244',
    regions: [{ name: 'Luanda', cities: ['Luanda', 'Viana'] }],
  },
  {
    code: 'MZ', name: 'Mozambique', nameFr: 'Mozambique', currency: 'MZN', currencySymbol: 'MT',
    timezone: 'Africa/Maputo', phoneCode: '+258',
    regions: [{ name: 'Maputo', cities: ['Maputo', 'Matola'] }],
  },
  {
    code: 'ZW', name: 'Zimbabwe', nameFr: 'Zimbabwe', currency: 'ZWL', currencySymbol: 'Z$',
    timezone: 'Africa/Harare', phoneCode: '+263',
    regions: [{ name: 'Harare', cities: ['Harare', 'Bulawayo'] }],
  },
  {
    code: 'ZM', name: 'Zambia', nameFr: 'Zambie', currency: 'ZMW', currencySymbol: 'ZK',
    timezone: 'Africa/Lusaka', phoneCode: '+260',
    regions: [{ name: 'Lusaka', cities: ['Lusaka', 'Ndola'] }],
  },
  {
    code: 'MW', name: 'Malawi', nameFr: 'Malawi', currency: 'MWK', currencySymbol: 'MK',
    timezone: 'Africa/Blantyre', phoneCode: '+265',
  },
  {
    code: 'BW', name: 'Botswana', nameFr: 'Botswana', currency: 'BWP', currencySymbol: 'P',
    timezone: 'Africa/Gaborone', phoneCode: '+267',
  },
  {
    code: 'NA', name: 'Namibia', nameFr: 'Namibie', currency: 'NAD', currencySymbol: 'N$',
    timezone: 'Africa/Windhoek', phoneCode: '+264',
  },
  {
    code: 'LS', name: 'Lesotho', nameFr: 'Lesotho', currency: 'LSL', currencySymbol: 'L',
    timezone: 'Africa/Maseru', phoneCode: '+266',
  },
  {
    code: 'SZ', name: 'Eswatini', nameFr: 'Eswatini', currency: 'SZL', currencySymbol: 'E',
    timezone: 'Africa/Mbabane', phoneCode: '+268',
  },
  {
    code: 'MG', name: 'Madagascar', nameFr: 'Madagascar', currency: 'MGA', currencySymbol: 'Ar',
    timezone: 'Indian/Antananarivo', phoneCode: '+261',
    regions: [{ name: 'Antananarivo', cities: ['Antananarivo', 'Toamasina'] }],
  },
  {
    code: 'MU', name: 'Mauritius', nameFr: 'Maurice', currency: 'MUR', currencySymbol: 'Rs',
    timezone: 'Indian/Mauritius', phoneCode: '+230',
  },
  {
    code: 'SC', name: 'Seychelles', nameFr: 'Seychelles', currency: 'SCR', currencySymbol: 'SR',
    timezone: 'Indian/Mahe', phoneCode: '+248',
  },
  {
    code: 'KM', name: 'Comoros', nameFr: 'Comores', currency: 'KMF', currencySymbol: 'CF',
    timezone: 'Indian/Comoro', phoneCode: '+269',
  },
  {
    code: 'CV', name: 'Cape Verde', nameFr: 'Cap-Vert', currency: 'CVE', currencySymbol: 'Esc',
    timezone: 'Atlantic/Cape_Verde', phoneCode: '+238',
  },
  {
    code: 'GW', name: 'Guinea-Bissau', nameFr: 'Guinée-Bissau', currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Bissau', phoneCode: '+245',
  },
  {
    code: 'GN', name: 'Guinea', nameFr: 'Guinée', currency: 'GNF', currencySymbol: 'FG',
    timezone: 'Africa/Conakry', phoneCode: '+224',
    regions: [{ name: 'Conakry', cities: ['Conakry', 'Kankan'] }],
  },
  {
    code: 'SL', name: 'Sierra Leone', nameFr: 'Sierra Leone', currency: 'SLL', currencySymbol: 'Le',
    timezone: 'Africa/Freetown', phoneCode: '+232',
  },
  {
    code: 'LR', name: 'Liberia', nameFr: 'Liberia', currency: 'LRD', currencySymbol: 'L$',
    timezone: 'Africa/Monrovia', phoneCode: '+231',
  },
  {
    code: 'MR', name: 'Mauritania', nameFr: 'Mauritanie', currency: 'MRU', currencySymbol: 'UM',
    timezone: 'Africa/Nouakchott', phoneCode: '+222',
  },
  {
    code: 'NE', name: 'Niger', nameFr: 'Niger', currency: 'XOF', currencySymbol: 'FCFA',
    timezone: 'Africa/Niamey', phoneCode: '+227',
  },
  {
    code: 'SO', name: 'Somalia', nameFr: 'Somalie', currency: 'SOS', currencySymbol: 'So.Sh.',
    timezone: 'Africa/Mogadishu', phoneCode: '+252',
  },
  {
    code: 'DJ', name: 'Djibouti', nameFr: 'Djibouti', currency: 'DJF', currencySymbol: 'Fdj',
    timezone: 'Africa/Djibouti', phoneCode: '+253',
  },
  {
    code: 'ER', name: 'Eritrea', nameFr: 'Érythrée', currency: 'ERN', currencySymbol: 'Nfk',
    timezone: 'Africa/Asmara', phoneCode: '+291',
  },
  {
    code: 'BI', name: 'Burundi', nameFr: 'Burundi', currency: 'BIF', currencySymbol: 'FBu',
    timezone: 'Africa/Bujumbura', phoneCode: '+257',
  },
  {
    code: 'ST', name: 'São Tomé and Príncipe', nameFr: 'São Tomé-et-Príncipe', currency: 'STN', currencySymbol: 'Db',
    timezone: 'Africa/Sao_Tome', phoneCode: '+239',
  },
];

const INTERNATIONAL: CountryInfo[] = [
  // ── Middle East ──
  { code: 'AE', name: 'United Arab Emirates', nameFr: 'Émirats Arabes Unis', currency: 'AED', currencySymbol: 'AED', timezone: 'Asia/Dubai', phoneCode: '+971',
    regions: [
      { name: 'Dubai', cities: ['Dubai', 'Deira', 'Jebel Ali'] },
      { name: 'Abu Dhabi', cities: ['Abu Dhabi', 'Al Ain'] },
      { name: 'Sharjah', cities: ['Sharjah', 'Khor Fakkan'] },
    ],
  },
  { code: 'SA', name: 'Saudi Arabia', nameFr: 'Arabie Saoudite', currency: 'SAR', currencySymbol: 'SR', timezone: 'Asia/Riyadh', phoneCode: '+966',
    regions: [
      { name: 'Riyadh', cities: ['Riyadh', 'Diriyah'] },
      { name: 'Makkah', cities: ['Jeddah', 'Mecca', 'Taif'] },
      { name: 'Eastern Province', cities: ['Dammam', 'Khobar', 'Jubail'] },
    ],
  },
  { code: 'QA', name: 'Qatar', nameFr: 'Qatar', currency: 'QAR', currencySymbol: 'QR', timezone: 'Asia/Qatar', phoneCode: '+974',
    regions: [{ name: 'Doha', cities: ['Doha', 'Al Rayyan'] }],
  },
  { code: 'KW', name: 'Kuwait', nameFr: 'Koweït', currency: 'KWD', currencySymbol: 'KD', timezone: 'Asia/Kuwait', phoneCode: '+965',
    regions: [{ name: 'Al Asimah', cities: ['Kuwait City', 'Hawalli'] }],
  },
  { code: 'BH', name: 'Bahrain', nameFr: 'Bahreïn', currency: 'BHD', currencySymbol: 'BD', timezone: 'Asia/Bahrain', phoneCode: '+973' },
  { code: 'OM', name: 'Oman', nameFr: 'Oman', currency: 'OMR', currencySymbol: 'OMR', timezone: 'Asia/Muscat', phoneCode: '+968',
    regions: [{ name: 'Muscat', cities: ['Muscat', 'Salalah'] }],
  },
  { code: 'JO', name: 'Jordan', nameFr: 'Jordanie', currency: 'JOD', currencySymbol: 'JD', timezone: 'Asia/Amman', phoneCode: '+962',
    regions: [{ name: 'Amman', cities: ['Amman', 'Zarqa'] }],
  },
  { code: 'LB', name: 'Lebanon', nameFr: 'Liban', currency: 'LBP', currencySymbol: 'LL', timezone: 'Asia/Beirut', phoneCode: '+961',
    regions: [{ name: 'Beirut', cities: ['Beirut', 'Tripoli'] }],
  },
  { code: 'IL', name: 'Israel', nameFr: 'Israël', currency: 'ILS', currencySymbol: '₪', timezone: 'Asia/Jerusalem', phoneCode: '+972',
    regions: [{ name: 'Tel Aviv', cities: ['Tel Aviv', 'Ramat Gan'] }, { name: 'Jerusalem', cities: ['Jerusalem'] }],
  },
  { code: 'PS', name: 'Palestine', nameFr: 'Palestine', currency: 'ILS', currencySymbol: '₪', timezone: 'Asia/Gaza', phoneCode: '+970' },
  { code: 'IQ', name: 'Iraq', nameFr: 'Irak', currency: 'IQD', currencySymbol: 'ID', timezone: 'Asia/Baghdad', phoneCode: '+964',
    regions: [{ name: 'Baghdad', cities: ['Baghdad', 'Basra'] }],
  },
  { code: 'IR', name: 'Iran', nameFr: 'Iran', currency: 'IRR', currencySymbol: 'Rial', timezone: 'Asia/Tehran', phoneCode: '+98',
    regions: [{ name: 'Tehran', cities: ['Tehran', 'Mashhad'] }],
  },
  { code: 'SY', name: 'Syria', nameFr: 'Syrie', currency: 'SYP', currencySymbol: 'SYP', timezone: 'Asia/Damascus', phoneCode: '+963' },
  { code: 'YE', name: 'Yemen', nameFr: 'Yémen', currency: 'YER', currencySymbol: 'YR', timezone: 'Asia/Aden', phoneCode: '+967' },
  { code: 'AF', name: 'Afghanistan', nameFr: 'Afghanistan', currency: 'AFN', currencySymbol: 'Af', timezone: 'Asia/Kabul', phoneCode: '+93' },
  { code: 'PK', name: 'Pakistan', nameFr: 'Pakistan', currency: 'PKR', currencySymbol: 'Rs', timezone: 'Asia/Karachi', phoneCode: '+92',
    regions: [{ name: 'Sindh', cities: ['Karachi', 'Hyderabad'] }, { name: 'Punjab', cities: ['Lahore', 'Faisalabad', 'Rawalpindi'] }],
  },

  // ── Europe ──
  { code: 'FR', name: 'France', nameFr: 'France', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Paris', phoneCode: '+33',
    regions: [
      { name: 'Île-de-France', cities: ['Paris', 'Versailles', 'Boulogne-Billancourt'] },
      { name: 'Auvergne-Rhône-Alpes', cities: ['Lyon', 'Grenoble', 'Clermont-Ferrand'] },
      { name: 'Provence-Alpes-Côte d\'Azur', cities: ['Marseille', 'Nice', 'Toulon'] },
      { name: 'Occitanie', cities: ['Toulouse', 'Montpellier'] },
      { name: 'Nouvelle-Aquitaine', cities: ['Bordeaux', 'Limoges'] },
      { name: 'Hauts-de-France', cities: ['Lille', 'Amiens'] },
      { name: 'Grand Est', cities: ['Strasbourg', 'Reims', 'Metz'] },
      { name: 'Pays de la Loire', cities: ['Nantes', 'Angers'] },
      { name: 'Bretagne', cities: ['Rennes', 'Brest'] },
      { name: 'Normandie', cities: ['Rouen', 'Caen'] },
    ],
  },
  { code: 'GB', name: 'United Kingdom', nameFr: 'Royaume-Uni', currency: 'GBP', currencySymbol: '£', timezone: 'Europe/London', phoneCode: '+44',
    regions: [
      { name: 'Greater London', cities: ['London', 'Westminster', 'Croydon'] },
      { name: 'Greater Manchester', cities: ['Manchester', 'Salford'] },
      { name: 'West Midlands', cities: ['Birmingham', 'Coventry'] },
      { name: 'Scotland', cities: ['Edinburgh', 'Glasgow', 'Aberdeen'] },
      { name: 'Wales', cities: ['Cardiff', 'Swansea'] },
      { name: 'Northern Ireland', cities: ['Belfast', 'Derry'] },
    ],
  },
  { code: 'DE', name: 'Germany', nameFr: 'Allemagne', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Berlin', phoneCode: '+49',
    regions: [
      { name: 'Bavaria', cities: ['Munich', 'Nuremberg', 'Augsburg'] },
      { name: 'Berlin', cities: ['Berlin'] },
      { name: 'Hamburg', cities: ['Hamburg'] },
      { name: 'Hesse', cities: ['Frankfurt', 'Wiesbaden'] },
      { name: 'North Rhine-Westphalia', cities: ['Cologne', 'Düsseldorf', 'Dortmund'] },
    ],
  },
  { code: 'ES', name: 'Spain', nameFr: 'Espagne', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Madrid', phoneCode: '+34',
    regions: [
      { name: 'Madrid', cities: ['Madrid', 'Alcalá de Henares'] },
      { name: 'Catalonia', cities: ['Barcelona', 'Girona', 'Tarragona'] },
      { name: 'Andalusia', cities: ['Seville', 'Málaga', 'Granada'] },
      { name: 'Valencia', cities: ['Valencia', 'Alicante'] },
    ],
  },
  { code: 'IT', name: 'Italy', nameFr: 'Italie', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Rome', phoneCode: '+39',
    regions: [
      { name: 'Lazio', cities: ['Rome', 'Latina'] },
      { name: 'Lombardy', cities: ['Milan', 'Bergamo', 'Brescia'] },
      { name: 'Campania', cities: ['Naples', 'Salerno'] },
      { name: 'Tuscany', cities: ['Florence', 'Pisa'] },
    ],
  },
  { code: 'PT', name: 'Portugal', nameFr: 'Portugal', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Lisbon', phoneCode: '+351',
    regions: [{ name: 'Lisbon', cities: ['Lisbon', 'Sintra', 'Cascais'] }, { name: 'Porto', cities: ['Porto', 'Vila Nova de Gaia'] }],
  },
  { code: 'NL', name: 'Netherlands', nameFr: 'Pays-Bas', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Amsterdam', phoneCode: '+31',
    regions: [{ name: 'North Holland', cities: ['Amsterdam', 'Haarlem'] }, { name: 'South Holland', cities: ['Rotterdam', 'The Hague'] }],
  },
  { code: 'BE', name: 'Belgium', nameFr: 'Belgique', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Brussels', phoneCode: '+32',
    regions: [{ name: 'Brussels', cities: ['Brussels'] }, { name: 'Flanders', cities: ['Antwerp', 'Ghent', 'Bruges'] }, { name: 'Wallonia', cities: ['Liège', 'Charleroi'] }],
  },
  { code: 'LU', name: 'Luxembourg', nameFr: 'Luxembourg', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Luxembourg', phoneCode: '+352' },
  { code: 'CH', name: 'Switzerland', nameFr: 'Suisse', currency: 'CHF', currencySymbol: 'CHF', timezone: 'Europe/Zurich', phoneCode: '+41',
    regions: [{ name: 'Zurich', cities: ['Zurich', 'Winterthur'] }, { name: 'Geneva', cities: ['Geneva'] }],
  },
  { code: 'AT', name: 'Austria', nameFr: 'Autriche', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Vienna', phoneCode: '+43',
    regions: [{ name: 'Vienna', cities: ['Vienna'] }],
  },
  { code: 'IE', name: 'Ireland', nameFr: 'Irlande', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Dublin', phoneCode: '+353',
    regions: [{ name: 'Leinster', cities: ['Dublin', 'Kilkenny'] }],
  },
  { code: 'SE', name: 'Sweden', nameFr: 'Suède', currency: 'SEK', currencySymbol: 'kr', timezone: 'Europe/Stockholm', phoneCode: '+46',
    regions: [{ name: 'Stockholm', cities: ['Stockholm', 'Solna'] }],
  },
  { code: 'NO', name: 'Norway', nameFr: 'Norvège', currency: 'NOK', currencySymbol: 'kr', timezone: 'Europe/Oslo', phoneCode: '+47',
    regions: [{ name: 'Oslo', cities: ['Oslo', 'Bærum'] }],
  },
  { code: 'DK', name: 'Denmark', nameFr: 'Danemark', currency: 'DKK', currencySymbol: 'kr', timezone: 'Europe/Copenhagen', phoneCode: '+45',
    regions: [{ name: 'Capital Region', cities: ['Copenhagen', 'Frederiksberg'] }],
  },
  { code: 'FI', name: 'Finland', nameFr: 'Finlande', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Helsinki', phoneCode: '+358',
    regions: [{ name: 'Uusimaa', cities: ['Helsinki', 'Espoo'] }],
  },
  { code: 'IS', name: 'Iceland', nameFr: 'Islande', currency: 'ISK', currencySymbol: 'kr', timezone: 'Atlantic/Reykjavik', phoneCode: '+354' },
  { code: 'PL', name: 'Poland', nameFr: 'Pologne', currency: 'PLN', currencySymbol: 'zł', timezone: 'Europe/Warsaw', phoneCode: '+48',
    regions: [{ name: 'Masovia', cities: ['Warsaw', 'Radom'] }],
  },
  { code: 'CZ', name: 'Czech Republic', nameFr: 'Tchéquie', currency: 'CZK', currencySymbol: 'Kč', timezone: 'Europe/Prague', phoneCode: '+420',
    regions: [{ name: 'Prague', cities: ['Prague'] }],
  },
  { code: 'SK', name: 'Slovakia', nameFr: 'Slovaquie', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Bratislava', phoneCode: '+421' },
  { code: 'HU', name: 'Hungary', nameFr: 'Hongrie', currency: 'HUF', currencySymbol: 'Ft', timezone: 'Europe/Budapest', phoneCode: '+36' },
  { code: 'RO', name: 'Romania', nameFr: 'Roumanie', currency: 'RON', currencySymbol: 'lei', timezone: 'Europe/Bucharest', phoneCode: '+40',
    regions: [{ name: 'Bucharest', cities: ['Bucharest'] }],
  },
  { code: 'BG', name: 'Bulgaria', nameFr: 'Bulgarie', currency: 'BGN', currencySymbol: 'lv', timezone: 'Europe/Sofia', phoneCode: '+359' },
  { code: 'GR', name: 'Greece', nameFr: 'Grèce', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Athens', phoneCode: '+30',
    regions: [{ name: 'Attica', cities: ['Athens', 'Piraeus'] }],
  },
  { code: 'HR', name: 'Croatia', nameFr: 'Croatie', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Zagreb', phoneCode: '+385',
    regions: [{ name: 'Zagreb', cities: ['Zagreb', 'Split'] }],
  },
  { code: 'SI', name: 'Slovenia', nameFr: 'Slovénie', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Ljubljana', phoneCode: '+386' },
  { code: 'RS', name: 'Serbia', nameFr: 'Serbie', currency: 'RSD', currencySymbol: 'din', timezone: 'Europe/Belgrade', phoneCode: '+381' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nameFr: 'Bosnie-Herzégovine', currency: 'BAM', currencySymbol: 'KM', timezone: 'Europe/Sarajevo', phoneCode: '+387' },
  { code: 'MK', name: 'North Macedonia', nameFr: 'Macédoine du Nord', currency: 'MKD', currencySymbol: 'den', timezone: 'Europe/Skopje', phoneCode: '+389' },
  { code: 'AL', name: 'Albania', nameFr: 'Albanie', currency: 'ALL', currencySymbol: 'L', timezone: 'Europe/Tirane', phoneCode: '+355' },
  { code: 'ME', name: 'Montenegro', nameFr: 'Monténégro', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Podgorica', phoneCode: '+382' },
  { code: 'EE', name: 'Estonia', nameFr: 'Estonie', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Tallinn', phoneCode: '+372' },
  { code: 'LV', name: 'Latvia', nameFr: 'Lettonie', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Riga', phoneCode: '+371' },
  { code: 'LT', name: 'Lithuania', nameFr: 'Lituanie', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Vilnius', phoneCode: '+370' },
  { code: 'UA', name: 'Ukraine', nameFr: 'Ukraine', currency: 'UAH', currencySymbol: '₴', timezone: 'Europe/Kyiv', phoneCode: '+380',
    regions: [{ name: 'Kyiv', cities: ['Kyiv', 'Bila Tserkva'] }],
  },
  { code: 'BY', name: 'Belarus', nameFr: 'Biélorussie', currency: 'BYN', currencySymbol: 'Br', timezone: 'Europe/Minsk', phoneCode: '+375' },
  { code: 'MD', name: 'Moldova', nameFr: 'Moldavie', currency: 'MDL', currencySymbol: 'L', timezone: 'Europe/Chisinau', phoneCode: '+373' },
  { code: 'RU', name: 'Russia', nameFr: 'Russie', currency: 'RUB', currencySymbol: '₽', timezone: 'Europe/Moscow', phoneCode: '+7',
    regions: [{ name: 'Moscow', cities: ['Moscow', 'Saint Petersburg'] }],
  },
  { code: 'GE', name: 'Georgia', nameFr: 'Géorgie', currency: 'GEL', currencySymbol: '₾', timezone: 'Asia/Tbilisi', phoneCode: '+995' },
  { code: 'AM', name: 'Armenia', nameFr: 'Arménie', currency: 'AMD', currencySymbol: '֏', timezone: 'Asia/Yerevan', phoneCode: '+374' },
  { code: 'AZ', name: 'Azerbaijan', nameFr: 'Azerbaïdjan', currency: 'AZN', currencySymbol: 'man', timezone: 'Asia/Baku', phoneCode: '+994' },
  { code: 'CY', name: 'Cyprus', nameFr: 'Chypre', currency: 'EUR', currencySymbol: '€', timezone: 'Asia/Nicosia', phoneCode: '+357' },
  { code: 'MT', name: 'Malta', nameFr: 'Malte', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Malta', phoneCode: '+356' },
  { code: 'TR', name: 'Türkiye', nameFr: 'Türkiye', currency: 'TRY', currencySymbol: '₺', timezone: 'Europe/Istanbul', phoneCode: '+90',
    regions: [{ name: 'Istanbul', cities: ['Istanbul', 'Ankara', 'Izmir'] }],
  },

  // ── North America ──
  { code: 'US', name: 'United States', nameFr: 'États-Unis', currency: 'USD', currencySymbol: '$', timezone: 'America/New_York', phoneCode: '+1',
    regions: [
      { name: 'California', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose'] },
      { name: 'New York', cities: ['New York', 'Buffalo', 'Rochester'] },
      { name: 'Texas', cities: ['Houston', 'Dallas', 'Austin', 'San Antonio'] },
      { name: 'Florida', cities: ['Miami', 'Orlando', 'Tampa'] },
      { name: 'Illinois', cities: ['Chicago', 'Springfield'] },
      { name: 'Washington', cities: ['Seattle', 'Spokane'] },
      { name: 'Massachusetts', cities: ['Boston', 'Cambridge'] },
    ],
  },
  { code: 'CA', name: 'Canada', nameFr: 'Canada', currency: 'CAD', currencySymbol: 'C$', timezone: 'America/Toronto', phoneCode: '+1',
    regions: [
      { name: 'Ontario', cities: ['Toronto', 'Ottawa', 'Mississauga'] },
      { name: 'Quebec', cities: ['Montreal', 'Quebec City'] },
      { name: 'British Columbia', cities: ['Vancouver', 'Victoria'] },
      { name: 'Alberta', cities: ['Calgary', 'Edmonton'] },
    ],
  },
  { code: 'MX', name: 'Mexico', nameFr: 'Mexique', currency: 'MXN', currencySymbol: '$', timezone: 'America/Mexico_City', phoneCode: '+52',
    regions: [{ name: 'Mexico City', cities: ['Mexico City', 'Ecatepec'] }, { name: 'Jalisco', cities: ['Guadalajara', 'Zapopan'] }],
  },

  // ── Central America & Caribbean ──
  { code: 'GT', name: 'Guatemala', nameFr: 'Guatemala', currency: 'GTQ', currencySymbol: 'Q', timezone: 'America/Guatemala', phoneCode: '+502' },
  { code: 'HN', name: 'Honduras', nameFr: 'Honduras', currency: 'HNL', currencySymbol: 'L', timezone: 'America/Tegucigalpa', phoneCode: '+504' },
  { code: 'SV', name: 'El Salvador', nameFr: 'El Salvador', currency: 'USD', currencySymbol: '$', timezone: 'America/El_Salvador', phoneCode: '+503' },
  { code: 'NI', name: 'Nicaragua', nameFr: 'Nicaragua', currency: 'NIO', currencySymbol: 'C$', timezone: 'America/Managua', phoneCode: '+505' },
  { code: 'CR', name: 'Costa Rica', nameFr: 'Costa Rica', currency: 'CRC', currencySymbol: '₡', timezone: 'America/Costa_Rica', phoneCode: '+506' },
  { code: 'PA', name: 'Panama', nameFr: 'Panama', currency: 'PAB', currencySymbol: 'B/.', timezone: 'America/Panama', phoneCode: '+507' },
  { code: 'CU', name: 'Cuba', nameFr: 'Cuba', currency: 'CUP', currencySymbol: '₱', timezone: 'America/Havana', phoneCode: '+53' },
  { code: 'DO', name: 'Dominican Republic', nameFr: 'République Dominicaine', currency: 'DOP', currencySymbol: 'RD$', timezone: 'America/Santo_Domingo', phoneCode: '+1' },
  { code: 'JM', name: 'Jamaica', nameFr: 'Jamaïque', currency: 'JMD', currencySymbol: 'J$', timezone: 'America/Jamaica', phoneCode: '+1' },
  { code: 'HT', name: 'Haiti', nameFr: 'Haïti', currency: 'HTG', currencySymbol: 'G', timezone: 'America/Port-au-Prince', phoneCode: '+509' },
  { code: 'BS', name: 'Bahamas', nameFr: 'Bahamas', currency: 'BSD', currencySymbol: 'B$', timezone: 'America/Nassau', phoneCode: '+1' },
  { code: 'TT', name: 'Trinidad and Tobago', nameFr: 'Trinité-et-Tobago', currency: 'TTD', currencySymbol: 'TT$', timezone: 'America/Port_of_Spain', phoneCode: '+1' },
  { code: 'BB', name: 'Barbados', nameFr: 'Barbade', currency: 'BBD', currencySymbol: 'Bds$', timezone: 'America/Barbados', phoneCode: '+1' },
  { code: 'BZ', name: 'Belize', nameFr: 'Belize', currency: 'BZD', currencySymbol: 'BZ$', timezone: 'America/Belize', phoneCode: '+501' },

  // ── South America ──
  { code: 'BR', name: 'Brazil', nameFr: 'Brésil', currency: 'BRL', currencySymbol: 'R$', timezone: 'America/Sao_Paulo', phoneCode: '+55',
    regions: [
      { name: 'São Paulo', cities: ['São Paulo', 'Campinas', 'Guarulhos'] },
      { name: 'Rio de Janeiro', cities: ['Rio de Janeiro', 'Niterói'] },
      { name: 'Bahia', cities: ['Salvador', 'Feira de Santana'] },
    ],
  },
  { code: 'AR', name: 'Argentina', nameFr: 'Argentine', currency: 'ARS', currencySymbol: '$', timezone: 'America/Argentina/Buenos_Aires', phoneCode: '+54',
    regions: [{ name: 'Buenos Aires', cities: ['Buenos Aires', 'La Plata'] }],
  },
  { code: 'CO', name: 'Colombia', nameFr: 'Colombie', currency: 'COP', currencySymbol: 'Col$', timezone: 'America/Bogota', phoneCode: '+57',
    regions: [{ name: 'Bogotá', cities: ['Bogotá', 'Soacha'] }, { name: 'Antioquia', cities: ['Medellín', 'Bello'] }],
  },
  { code: 'PE', name: 'Peru', nameFr: 'Pérou', currency: 'PEN', currencySymbol: 'S/', timezone: 'America/Lima', phoneCode: '+51',
    regions: [{ name: 'Lima', cities: ['Lima', 'Callao'] }],
  },
  { code: 'CL', name: 'Chile', nameFr: 'Chili', currency: 'CLP', currencySymbol: 'CL$', timezone: 'America/Santiago', phoneCode: '+56',
    regions: [{ name: 'Santiago', cities: ['Santiago', 'Puente Alto'] }],
  },
  { code: 'VE', name: 'Venezuela', nameFr: 'Venezuela', currency: 'VES', currencySymbol: 'Bs', timezone: 'America/Caracas', phoneCode: '+58' },
  { code: 'EC', name: 'Ecuador', nameFr: 'Équateur', currency: 'USD', currencySymbol: '$', timezone: 'America/Guayaquil', phoneCode: '+593',
    regions: [{ name: 'Pichincha', cities: ['Quito'] }, { name: 'Guayas', cities: ['Guayaquil'] }],
  },
  { code: 'BO', name: 'Bolivia', nameFr: 'Bolivie', currency: 'BOB', currencySymbol: 'Bs', timezone: 'America/La_Paz', phoneCode: '+591' },
  { code: 'PY', name: 'Paraguay', nameFr: 'Paraguay', currency: 'PYG', currencySymbol: '₲', timezone: 'America/Asuncion', phoneCode: '+595' },
  { code: 'UY', name: 'Uruguay', nameFr: 'Uruguay', currency: 'UYU', currencySymbol: '$U', timezone: 'America/Montevideo', phoneCode: '+598' },
  { code: 'GY', name: 'Guyana', nameFr: 'Guyana', currency: 'GYD', currencySymbol: 'G$', timezone: 'America/Guyana', phoneCode: '+592' },
  { code: 'SR', name: 'Suriname', nameFr: 'Suriname', currency: 'SRD', currencySymbol: 'Sr$', timezone: 'America/Paramaribo', phoneCode: '+597' },

  // ── Asia ──
  { code: 'CN', name: 'China', nameFr: 'Chine', currency: 'CNY', currencySymbol: '¥', timezone: 'Asia/Shanghai', phoneCode: '+86',
    regions: [
      { name: 'Beijing', cities: ['Beijing'] },
      { name: 'Shanghai', cities: ['Shanghai'] },
      { name: 'Guangdong', cities: ['Guangzhou', 'Shenzhen'] },
    ],
  },
  { code: 'JP', name: 'Japan', nameFr: 'Japon', currency: 'JPY', currencySymbol: '¥', timezone: 'Asia/Tokyo', phoneCode: '+81',
    regions: [{ name: 'Tokyo', cities: ['Tokyo', 'Yokohama'] }, { name: 'Osaka', cities: ['Osaka', 'Sakai'] }],
  },
  { code: 'KR', name: 'South Korea', nameFr: 'Corée du Sud', currency: 'KRW', currencySymbol: '₩', timezone: 'Asia/Seoul', phoneCode: '+82',
    regions: [{ name: 'Seoul', cities: ['Seoul', 'Incheon'] }],
  },
  { code: 'KP', name: 'North Korea', nameFr: 'Corée du Nord', currency: 'KPW', currencySymbol: '₩', timezone: 'Asia/Pyongyang', phoneCode: '+850' },
  { code: 'IN', name: 'India', nameFr: 'Inde', currency: 'INR', currencySymbol: '₹', timezone: 'Asia/Kolkata', phoneCode: '+91',
    regions: [
      { name: 'Maharashtra', cities: ['Mumbai', 'Pune', 'Nagpur'] },
      { name: 'Delhi', cities: ['New Delhi', 'Delhi'] },
      { name: 'Karnataka', cities: ['Bangalore', 'Mysore'] },
      { name: 'Tamil Nadu', cities: ['Chennai', 'Coimbatore'] },
      { name: 'West Bengal', cities: ['Kolkata'] },
    ],
  },
  { code: 'BD', name: 'Bangladesh', nameFr: 'Bangladesh', currency: 'BDT', currencySymbol: '৳', timezone: 'Asia/Dhaka', phoneCode: '+880',
    regions: [{ name: 'Dhaka', cities: ['Dhaka', 'Chittagong'] }],
  },
  { code: 'LK', name: 'Sri Lanka', nameFr: 'Sri Lanka', currency: 'LKR', currencySymbol: 'Rs', timezone: 'Asia/Colombo', phoneCode: '+94' },
  { code: 'NP', name: 'Nepal', nameFr: 'Népal', currency: 'NPR', currencySymbol: 'Rs', timezone: 'Asia/Kathmandu', phoneCode: '+977' },
  { code: 'MM', name: 'Myanmar', nameFr: 'Myanmar', currency: 'MMK', currencySymbol: 'K', timezone: 'Asia/Yangon', phoneCode: '+95' },
  { code: 'TH', name: 'Thailand', nameFr: 'Thaïlande', currency: 'THB', currencySymbol: '฿', timezone: 'Asia/Bangkok', phoneCode: '+66',
    regions: [{ name: 'Bangkok', cities: ['Bangkok'] }],
  },
  { code: 'KH', name: 'Cambodia', nameFr: 'Cambodge', currency: 'KHR', currencySymbol: '៛', timezone: 'Asia/Phnom_Penh', phoneCode: '+855' },
  { code: 'LA', name: 'Laos', nameFr: 'Laos', currency: 'LAK', currencySymbol: '₭', timezone: 'Asia/Vientiane', phoneCode: '+856' },
  { code: 'VN', name: 'Vietnam', nameFr: 'Vietnam', currency: 'VND', currencySymbol: '₫', timezone: 'Asia/Ho_Chi_Minh', phoneCode: '+84',
    regions: [{ name: 'Ho Chi Minh City', cities: ['Ho Chi Minh City', 'Hanoi'] }],
  },
  { code: 'SG', name: 'Singapore', nameFr: 'Singapour', currency: 'SGD', currencySymbol: 'S$', timezone: 'Asia/Singapore', phoneCode: '+65' },
  { code: 'MY', name: 'Malaysia', nameFr: 'Malaisie', currency: 'MYR', currencySymbol: 'RM', timezone: 'Asia/Kuala_Lumpur', phoneCode: '+60',
    regions: [{ name: 'Kuala Lumpur', cities: ['Kuala Lumpur'] }],
  },
  { code: 'ID', name: 'Indonesia', nameFr: 'Indonésie', currency: 'IDR', currencySymbol: 'Rp', timezone: 'Asia/Jakarta', phoneCode: '+62',
    regions: [{ name: 'Jakarta', cities: ['Jakarta', 'Bekasi'] }],
  },
  { code: 'PH', name: 'Philippines', nameFr: 'Philippines', currency: 'PHP', currencySymbol: '₱', timezone: 'Asia/Manila', phoneCode: '+63',
    regions: [{ name: 'Metro Manila', cities: ['Manila', 'Quezon City'] }],
  },
  { code: 'BN', name: 'Brunei', nameFr: 'Brunei', currency: 'BND', currencySymbol: 'B$', timezone: 'Asia/Brunei', phoneCode: '+673' },
  { code: 'TL', name: 'Timor-Leste', nameFr: 'Timor oriental', currency: 'USD', currencySymbol: '$', timezone: 'Asia/Dili', phoneCode: '+670' },
  { code: 'TW', name: 'Taiwan', nameFr: 'Taïwan', currency: 'TWD', currencySymbol: 'NT$', timezone: 'Asia/Taipei', phoneCode: '+886',
    regions: [{ name: 'Taipei', cities: ['Taipei', 'Kaohsiung'] }],
  },
  { code: 'HK', name: 'Hong Kong', nameFr: 'Hong Kong', currency: 'HKD', currencySymbol: 'HK$', timezone: 'Asia/Hong_Kong', phoneCode: '+852' },
  { code: 'MO', name: 'Macao', nameFr: 'Macao', currency: 'MOP', currencySymbol: 'MOP$', timezone: 'Asia/Macau', phoneCode: '+853' },
  { code: 'MN', name: 'Mongolia', nameFr: 'Mongolie', currency: 'MNT', currencySymbol: '₮', timezone: 'Asia/Ulaanbaatar', phoneCode: '+976' },
  { code: 'KZ', name: 'Kazakhstan', nameFr: 'Kazakhstan', currency: 'KZT', currencySymbol: '₸', timezone: 'Asia/Almaty', phoneCode: '+7',
    regions: [{ name: 'Almaty', cities: ['Almaty', 'Astana'] }],
  },
  { code: 'UZ', name: 'Uzbekistan', nameFr: 'Ouzbékistan', currency: 'UZS', currencySymbol: 'so\'m', timezone: 'Asia/Tashkent', phoneCode: '+998' },
  { code: 'KG', name: 'Kyrgyzstan', nameFr: 'Kirghizistan', currency: 'KGS', currencySymbol: 'som', timezone: 'Asia/Bishkek', phoneCode: '+996' },
  { code: 'TJ', name: 'Tajikistan', nameFr: 'Tadjikistan', currency: 'TJS', currencySymbol: 'somoni', timezone: 'Asia/Dushanbe', phoneCode: '+992' },
  { code: 'TM', name: 'Turkmenistan', nameFr: 'Turkménistan', currency: 'TMT', currencySymbol: 'm', timezone: 'Asia/Ashgabat', phoneCode: '+993' },

  // ── Oceania ──
  { code: 'AU', name: 'Australia', nameFr: 'Australie', currency: 'AUD', currencySymbol: 'A$', timezone: 'Australia/Sydney', phoneCode: '+61',
    regions: [
      { name: 'New South Wales', cities: ['Sydney', 'Newcastle'] },
      { name: 'Victoria', cities: ['Melbourne', 'Geelong'] },
      { name: 'Queensland', cities: ['Brisbane', 'Gold Coast'] },
      { name: 'Western Australia', cities: ['Perth'] },
    ],
  },
  { code: 'NZ', name: 'New Zealand', nameFr: 'Nouvelle-Zélande', currency: 'NZD', currencySymbol: 'NZ$', timezone: 'Pacific/Auckland', phoneCode: '+64',
    regions: [{ name: 'Auckland', cities: ['Auckland', 'Wellington'] }],
  },
  { code: 'FJ', name: 'Fiji', nameFr: 'Fidji', currency: 'FJD', currencySymbol: 'FJ$', timezone: 'Pacific/Fiji', phoneCode: '+679' },
  { code: 'PG', name: 'Papua New Guinea', nameFr: 'Papouasie-Nouvelle-Guinée', currency: 'PGK', currencySymbol: 'K', timezone: 'Pacific/Port_Moresby', phoneCode: '+675' },
  { code: 'WS', name: 'Samoa', nameFr: 'Samoa', currency: 'WST', currencySymbol: 'WS$', timezone: 'Pacific/Apia', phoneCode: '+685' },
  { code: 'TO', name: 'Tonga', nameFr: 'Tonga', currency: 'TOP', currencySymbol: 'T$', timezone: 'Pacific/Tongatapu', phoneCode: '+676' },
  { code: 'VU', name: 'Vanuatu', nameFr: 'Vanuatu', currency: 'VUV', currencySymbol: 'VT', timezone: 'Pacific/Efate', phoneCode: '+678' },
  { code: 'SB', name: 'Solomon Islands', nameFr: 'Îles Salomon', currency: 'SBD', currencySymbol: 'SI$', timezone: 'Pacific/Guadalcanal', phoneCode: '+677' },
  { code: 'KI', name: 'Kiribati', nameFr: 'Kiribati', currency: 'AUD', currencySymbol: 'A$', timezone: 'Pacific/Tarawa', phoneCode: '+686' },

  // ── Micro-states ──
  { code: 'MC', name: 'Monaco', nameFr: 'Monaco', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Monaco', phoneCode: '+377' },
  { code: 'AD', name: 'Andorra', nameFr: 'Andorre', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Andorra', phoneCode: '+376' },
  { code: 'SM', name: 'San Marino', nameFr: 'Saint-Marin', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/San_Marino', phoneCode: '+378' },
  { code: 'VA', name: 'Vatican City', nameFr: 'Cité du Vatican', currency: 'EUR', currencySymbol: '€', timezone: 'Europe/Vatican', phoneCode: '+379' },
  { code: 'LI', name: 'Liechtenstein', nameFr: 'Liechtenstein', currency: 'CHF', currencySymbol: 'CHF', timezone: 'Europe/Vaduz', phoneCode: '+423' },
];

export const COUNTRIES: CountryInfo[] = [...AFRICA, ...INTERNATIONAL].sort((a, b) =>
  a.nameFr.localeCompare(b.nameFr),
);

export function getCountry(code: string): CountryInfo | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export const PAYMENT_METHODS = [
  { id: 'bank', labelFr: 'Virement bancaire', labelEn: 'Bank transfer' },
  { id: 'wave', labelFr: 'Wave', labelEn: 'Wave' },
  { id: 'orange', labelFr: 'Orange Money', labelEn: 'Orange Money' },
  { id: 'mtn', labelFr: 'MTN Mobile Money', labelEn: 'MTN Mobile Money' },
  { id: 'moov', labelFr: 'Moov Money', labelEn: 'Moov Money' },
  { id: 'mpesa', labelFr: 'M-Pesa', labelEn: 'M-Pesa' },
  { id: 'paypal', labelFr: 'PayPal', labelEn: 'PayPal' },
  { id: 'wise', labelFr: 'Wise Transfer', labelEn: 'Wise Transfer' },
  { id: 'stripe', labelFr: 'Carte bancaire (Stripe)', labelEn: 'Bank card (Stripe)' },
  { id: 'cash', labelFr: 'Espèces', labelEn: 'Cash' },
  { id: 'cheque', labelFr: 'Chèque', labelEn: 'Cheque' },
];
